### ISSUE TITLE
Thread deadlock issue in shell mode

### ISSUE THREAD

**Issue by keithrbennett** [keithrbennett/wifiwand#13]
I am getting the following error running the 'ci' (connected to Internet?) command, but only when in shell mode (that is, when it is executed within a pry session):

```[1] pry(#<WifiWand::CommandLineInterface>)> ci
Calling dig on domains ["google.com", "baidu.com"]...
fatal: No live threads left. Deadlock?
3 threads, 3 sleeps current:0x00007fbd13d0c5a0 main thread:0x00007fbd13d0c5a0
* #<Thread:0x00007fbd14069c20 sleep_forever>
   rb_thread_t:0x00007fbd13d0c5a0 native:0x00007fff89c2b380 int:0
   /Users/kbennett/work/wifi-wand/lib/wifi-wand/models/base_model.rb:89:in `join'
   /Users/kbennett/work/wifi-wand/lib/wifi-wand/models/base_model.rb:89:in `each'
   /Users/kbennett/work/wifi-wand/lib/wifi-wand/models/base_model.rb:89:in `block in connected_to_internet?'
   /Users/kbennett/work/wifi-wand/lib/wifi-wand/models/base_model.rb:126:in `connected_to_internet?'
   /Users/kbennett/work/wifi-wand/lib/wifi-wand/command_line_interface.rb:264:in `cmd_ci'
```

This code has not been changed in a while, and I have no idea why it's an issue now. This is the code that generates the error (it's `join` that produces the error):

```
domains = %w(google.com  baidu.com)
puts "Calling dig on domains #{domains}..." if @verbose_mode

threads = domains.map do |domain|
  Thread.new do
    output = `dig +short #{domain}`
    output.length > 0
  end
end

threads.each(&:join)
```

**Comment by bbs-software** [comment]
Strangely, this problem was solved by uninstalling and reinstalling the awesome_print gem.

**Comment by keithrbennett** [comment]
Strangely, this problem was solved by uninstalling and reinstalling the awesome_print gem.
