### ISSUE TITLE
Error "Wifi could not be disabled" on command `wifi-wand off`... while the command is working!

### ISSUE THREAD

**Issue by arnlen** [keithrbennett/wifiwand#23]
When running the command `wifi-wand off`, the wifi is properly turned off.
However, an error is raised:

```sh
Error: /Users/me/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/wifi-wand-2.15.0/lib/wifi-wand/models/mac_os_model.rb:209:in `wifi_off'
/Users/me/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/wifi-wand-2.15.0/lib/wifi-wand/command_line_interface.rb:377:in `cmd_of'
/Users/me/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/wifi-wand-2.15.0/lib/wifi-wand/command_line_interface.rb:479:in `block in commands'
/Users/me/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/wifi-wand-2.15.0/lib/wifi-wand/command_line_interface.rb:207:in `attempt_command_action'
/Users/me/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/wifi-wand-2.15.0/lib/wifi-wand/command_line_interface.rb:232:in `process_command_line'
/Users/me/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/wifi-wand-2.15.0/lib/wifi-wand/command_line_interface.rb:519:in `call'
/Users/me/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/wifi-wand-2.15.0/lib/wifi-wand/main.rb:65:in `call'
/Users/me/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/wifi-wand-2.15.0/exe/wifi-wand:5:in `<top (required)>'
/Users/me/.rbenv/versions/3.3.0/bin/wifi-wand:25:in `load'
/Users/me/.rbenv/versions/3.3.0/bin/wifi-wand:25:in `<main>'

Wifi could not be disabled.
```

## To reproduce

Just run:

```bash
$ wifi-wand off
```

## Configuration

- macOS Sonoma 14.4.1 (23E224)
- ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-darwin23]
- wifi-wand (2.15.0)

---

Thank you for this great gem! 🙌

**Comment by keithrbennett** [comment]
This was due to the `wifi_on?` method not working properly due to the `airport` deprecation.

I have fixed that method to use `networksetup` instead, and that fixes the problem.

Please `gem install wifi-wand` and get version 2.16.0, which fixes this and some other issues.
